export const UserApiUrl='auth'
export const CartApiUrl='carts'
export const LearnApiUrl='sign'
export const TestApiUrl='tests'
export const BookApiUrl='books'
export const OrderApiUrl='orders'
export const ResultApiUrl='result'


export const HomePageUrl='/'
export const ReportPageUrl='/report'
export const AboutPageUrl='/about'
export const ContactPageUrl='/contact'
export const UserPageUrl='/users'
export const LearnPageUrl='/learn'
export const TestPageUrl='/test'
export const ResultPageUrl='/result'
export const HistoryPageUrl='/history'